version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: appdb
      PGDATA: /var/lib/postgresql/data/db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/db
      - ./data/config/postgresql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    ports:
      - "5432:5432"
    networks:
      - traefik
  task_managment_api:
    container_name: task_managment_api
    build:
      context: ./api
      target: builder
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./api:/go/src/app
    depends_on:
      - postgres
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"
    networks:
      - traefik


networks:
  traefik:
    driver: bridge
